name: plt_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - r-cvms>=1.5.0
  - r-dplyr
  - r-ggplot2
  - r-ggimage>=0.3.3
  - r-rsvg
  - r-optparse
  - r-ggnewscale
  - r-stringr
  - r-jsonlite
  
